---
title: "Arkansas Lynchings Projext"
author: "Mary Hennigan" 
date: "8/26/2021"
output:
---

# Part 1: Import Data, Clean It

```{r include=FALSE}
#install.packages("slider")
#install.packages("zoo")
#install.packages("gtools")
# vignette("basic-usage", package="googlesheets")
#install.packages("googledrive")
#install.packages("googlesheets4")
library(tidyverse)
library(janitor)
library(lubridate)
library(tidyr)
library(jsonlite)
library(gtools)
library(zoo)
library(reshape2)
library(slider)
library(rio)
library(dplyr)
```

#--------------------------------------------------------------------#
#--------------------------------------------------------------------#
#Part 1: Analysis
#--------------------------------------------------------------------#
#--------------------------------------------------------------------#

#Import .csv from computer 

```{r}
lynchings <- rio::import("/Users/maryhennigan/Downloads/Lynching Project Fall 2021/Lynch1910_1919.csv")

glimpse(lynchings)
```

```{r}
ar_lynchings <- lynchings %>% 
  filter(state == 'AR')

ar_lynchings
write.csv(ar_lynchings, "ar_lynchings.csv")

#Arkansas has 40 lynchings reported from 1910 - 1919
```

```{r}
years <- ar_lynchings %>% 
  count(year)
write.csv(years, "years.csv")

#1919 has the most records with 10, then 1915 with seven, followed by 1911 with six.
```


```{r}
county <- ar_lynchings %>% 
  count(county) %>% 
  arrange(n)
write.csv(county, "county.csv")

#St. Francis (45 miles west of Memphis) has the most lynchings of this decade, four. Union, Lincoln and Garland counties follow with three lynchings each. 
```




